### ISSUE TITLE
Supportability on jaco.js 

### ISSUE THREAD

**Issue by pckoay** [jaco-project/jaco-js#11]
We are using jaco.js to implement Japanese transliteration solution. Hence, we would like to check with you on the following:-
1)	If we have enquiries/concerns when using jaco.js, how can we raise our questions? How soon we can get respond from you?
2)	If we encounter errors/issues when using jaco.js, how can we get support on this matter?
3)	If there is a new release on this library, how can we get notified so that we can test on it?

**Comment by saphryn** [comment]
Hello pckoay,

I'm Saphryn, and I've recently been put in charge to handle all English correspondence.
I've translated your post and will discuss your questions with the dev team today.

Thank you for your patience. You'll hear back from us very soon!
